import keymirror from "keymirror"
import *  as ForgetPassword from './ForgotPassword'
import * as NoteLoad from './NoteLoad'
import * as ResetPassword from './ResetPassword'

const ActionTypes = keymirror({
  SUBMIT_INVITE_ACTION: null,

//   LOGIN_REQUEST: null,
//   LOGIN_SUCCESS: null,
//   LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,

  SET_NAV_BAR_TITLE: null,

  CLEAR_NAV_BAR_TITLE: null,

//   FORGOT_PASSWORD_REQUEST: null,
//   FORGOT_PASSWORD_SUCCESS: null,
//   FORGOT_PASSWORD_FAILURE: null,

//   RESET_PASSWORD_REQUEST: null,
//   RESET_PASSWORD_SUCCESS: null,
//   RESET_PASSWORD_FAILURE: null,

  CLIENT_TOGGLE_FAVORITE_REQUEST: null,
  CLIENT_TOGGLE_FAVORITE_SUCCESS: null,
  CLIENT_TOGGLE_FAVORITE_ERROR: null,

  CLIENTS_LOAD_REQUEST: null,
  CLIENTS_LOAD_SUCCESS: null,
  CLIENTS_LOAD_FAILURE: null,

  GET_CURRENT_CLIENT_REQUEST: null,
  GET_CURRENT_CLIENT_SUCCESS: null,
  GET_CURRENT_CLIENT_FAILURE: null,

  CLIENT_COLLABORATORS_LOAD_REQUEST: null,
  CLIENT_COLLABORATORS_LOAD_SUCCESS: null,
  CLIENT_COLLABORATORS_LOAD_FAILURE: null,

  FETCH_UNASSIGNED_PEOPLE_REQUEST: null,
  FETCH_UNASSIGNED_PEOPLE_SUCCESS: null,
  FETCH_UNASSIGNED_PEOPLE_FAILURE: null,

  CLIENT_FETCH_COLLABORATOR_REQUESTS_REQUEST: null,
  CLIENT_FETCH_COLLABORATOR_REQUESTS_SUCCESS: null,
  CLIENT_FETCH_COLLABORATOR_REQUESTS_FAILURE: null,

  UPDATE_COLLABORATOR_ROLE_REQUEST: null,
  UPDATE_COLLABORATOR_ROLE_SUCCESS: null,
  UPDATE_COLLABORATOR_ROLE_FAILURE: null,

  REMOVE_COLLABORATOR_REQUEST: null,
  REMOVE_COLLABORATOR_SUCCESS: null,
  REMOVE_COLLABORATOR_FAILURE: null,

  TOGGLE_COLLABORATOR_STATUS_REQUEST: null,
  TOGGLE_COLLABORATOR_STATUS_SUCCESS: null,
  TOGGLE_COLLABORATOR_STATUS_FAILURE: null,

  CREATE_CLIENT_COLLABORATOR_REQUEST: null,
  CREATE_CLIENT_COLLABORATOR_SUCCESS: null,
  CREATE_CLIENT_COLLABORATOR_FAILURE: null,

  FETCH_CLIENT_OWNER_REQUEST: null,
  FETCH_CLIENT_OWNER_SUCCESS: null,
  FETCH_CLIENT_OWNER_FAILURE: null,

  LEAVE_CLIENT_REQUEST: null,
  LEAVE_CLIENT_SUCCESS: null,
  LEAVE_CLIENT_FAILURE: null,

  CLIENT_COLLABORATOR_AUTOSUGGEST_REQUEST: null,
  CLIENT_COLLABORATOR_AUTOSUGGEST_SUCCESS: null,
  CLIENT_COLLABORATOR_AUTOSUGGEST_FAILURE: null,

  TRANSFER_CLIENT_OWNERSHIP_REQUEST: null,
  TRANSFER_CLIENT_OWNERSHIP_SUCCESS: null,
  TRANSFER_CLIENT_OWNERSHIP_FAILURE: null,

  ACCEPT_COLLABORATOR_ACCESS_REQUEST: null,
  ACCEPT_COLLABORATOR_ACCESS_SUCCESS: null,
  ACCEPT_COLLABORATOR_ACCESS_FAILURE: null,

  REJECT_COLLABORATOR_ACCESS_REQUEST: null,
  REJECT_COLLABORATOR_ACCESS_SUCCESS: null,
  REJECT_COLLABORATOR_ACCESS_FAILURE: null,

  PEOPLE_LOAD_REQUEST: null,
  PEOPLE_LOAD_SUCCESS: null,
  PEOPLE_LOAD_FAILURE: null,

  PEOPLE_FILTERED_LOAD_REQUEST: null,

  CANCEL_PENDING_INVITE_REQUEST: null,
  CANCEL_PENDING_INVITE_SUCCESS: null,
  CANCEL_PENDING_INVITE_FAILURE: null,

  CANCEL_INVITE_REQUEST: null,
  CANCEL_INVITE_SUCCESS: null,
  CANCEL_INVITE_FAILURE: null,

  DELETE_PEOPLE: null,
  DELETE_PEOPLE_REQUEST: null,
  DELETE_PEOPLE_SUCCESS: null,
  DELETE_PEOPLE_FAILURE: null,

  UPLOAD_AVATAR_REQUEST: null,
  UPLOAD_AVATAR_SUCCESS: null,
  UPLOAD_AVATAR_FAILURE: null,

  CONTACTS_LOAD_REQUEST: null,
  CONTACTS_LOAD_SUCCESS: null,
  CONTACTS_LOAD_FAILURE: null,

 

  CONTACT_NOTES_UPDATE_REQUEST: null,
  CONTACT_NOTES_UPDATE_SUCCESS: null,
  CONTACT_NOTES_UPDATE_FAILURE: null,

  CONTACT_NOTES_DELETE_REQUEST: null,
  CONTACT_NOTES_DELETE_SUCCESS: null,
  CONTACT_NOTES_DELETE_FAILURE: null,

  CONTACT_TAGS_FETCH_REQUEST: null,
  CONTACT_TAGS_FETCH_SUCCESS: null,
  CONTACT_TAGS_FETCH_FAILURE: null,

  CONTACT_TAGS_CREATE_REQUEST: null,
  CONTACT_TAGS_CREATE_SUCCESS: null,
  CONTACT_TAGS_CREATE_FAILURE: null,

  CONTACT_TAGS_REMOVE_REQUEST: null,
  CONTACT_TAGS_REMOVE_SUCCESS: null,
  CONTACT_TAGS_REMOVE_FAILURE: null,

  GUESTS_LOAD_REQUEST: null,
  GUESTS_LOAD_SUCCESS: null,
  GUESTS_LOAD_FAILURE: null,

  GUEST_NOTES_LOAD_REQUEST: null,
  GUEST_NOTES_LOAD_SUCCESS: null,
  GUEST_NOTES_LOAD_FAILURE: null,

  GUEST_NOTES_CREATE_REQUEST: null,
  GUEST_NOTES_CREATE_SUCCESS: null,
  GUEST_NOTES_CREATE_FAILURE: null,

  GUEST_NOTES_UPDATE_REQUEST: null,
  GUEST_NOTES_UPDATE_SUCCESS: null,
  GUEST_NOTES_UPDATE_FAILURE: null,

  GUEST_NOTES_DELETE_REQUEST: null,
  GUEST_NOTES_DELETE_SUCCESS: null,
  GUEST_NOTES_DELETE_FAILURE: null,

  GUEST_TAGS_FETCH_REQUEST: null,
  GUEST_TAGS_FETCH_SUCCESS: null,
  GUEST_TAGS_FETCH_FAILURE: null,

  GUEST_TAGS_ADD_REQUEST: null,
  GUEST_TAGS_ADD_SUCCESS: null,
  GUEST_TAGS_ADD_FAILURE: null,

  GUEST_TAGS_CREATE_REQUEST: null,
  GUEST_TAGS_CREATE_SUCCESS: null,
  GUEST_TAGS_CREATE_FAILURE: null,

  GUEST_TAGS_REMOVE_REQUEST: null,
  GUEST_TAGS_REMOVE_SUCCESS: null,
  GUEST_TAGS_REMOVE_FAILURE: null,

  GUEST_LIST_ADDITION_REQUEST: null,
  GUEST_LIST_ADDITION_SUCCESS: null,
  GUEST_LIST_ADDITION_FAILURE: null,

  GUEST_LIST_BUILD_REQUEST: null,
  GUEST_LIST_BUILD_SUCCESS: null,
  GUEST_LIST_BUILD_FAILURE: null,

  GUEST_LIST_UPLOAD_REQUEST: null,
  GUEST_LIST_UPLOAD_SUCCESS: null,
  GUEST_LIST_UPLOAD_FAILURE: null,

  GUEST_LIST_RESET_MAPPING_REQUEST: null,

  GUEST_LIST_UNSUPPORTED_FILE: null,

  CREATE_GUEST_RESERVATION_REQUEST: null,
  CREATE_GUEST_RESERVATION_SUCCESS: null,
  CREATE_GUEST_RESERVATION_FAILURE: null,

  SET_CURRENT_CLIENT: null,
  SET_CURRENT_GUEST: null,

  // fetch a query from the reporting API
  FETCH_REPORT_QUERY_REQUEST: null,
  FETCH_REPORT_QUERY_SUCCESS: null,
  FETCH_REPORT_QUERY_FAILURE: null,

  ERROR_ALERT_MESSAGE: null,
  SUCCESS_ALERT_MESSAGE: null,
  INFO_ALERT_MESSAGE: null,
  WARNING_ALERT_MESSAGE: null,
  CLEAR_ALERT_MESSAGE: null,

  APPLY_CONTACTS_FILTERS: null,
  APPLY_AUDIENCE_FILTER: null,
  CLEAR_CONTACTS_FILTERS: null,
  CHANGE_CONTACTS_SEARCH_STRING: null,
  UPDATE_ARRAY_CONTACT_FILTER: null,
  UPDATE_SIMPLE_CONTACT_FILTER: null,
  CLEAR_SELECTED_CONTACT_PRESET: null,

  FETCH_FILTER_PRESETS_REQUEST: null,
  FETCH_FILTER_PRESETS_SUCCESS: null,
  FETCH_FILTER_PRESETS_FAILURE: null,

  SAVE_FILTER_PRESET_REQUEST: null,
  SAVE_FILTER_PRESET_SUCCESS: null,
  SAVE_FILTER_PRESETS_FAILURE: null,

  UPDATE_CLIENT_FILTERS: null,
  RESET_CLIENT_FILTERS: null,

  GET_ACCOUNT_LIST_REQUEST: null,
  GET_ACCOUNT_LIST_SUCCESS: null,
  GET_ACCOUNT_LIST_FAILURE: null,

  UPDATE_ACCOUNT_LIST_REQUEST: null,
  UPDATE_ACCOUNT_LIST_SUCCESS: null,
  UPDATE_ACCOUNT_LIST_FAILURE: null,

  GET_SUGGESTION_CARDS_REQUEST: null,
  GET_SUGGESTION_CARDS_SUCCESS: null,
  GET_SUGGESTION_CARDS_FAILURE: null,

  UPDATE_PEOPLE_ROLE_REQUEST: null,
  UPDATE_PEOPLE_ROLE_SUCCESS: null,
  UPDATE_PEOPLE_ROLE_FAILURE: null,

  GET_ID_LIST_REQUEST: null,
  GET_ID_LIST_SUCCESS: null,
  GET_ID_LIST_FAILURE: null,

  CONNECT_FACEBOOK_ID_REQUEST: null,
  CONNECT_FACEBOOK_ID_SUCCESS: null,
  CONNECT_FACEBOOK_ID_FAILURE: null,

  ADD_MEDIA_REQUEST: null,
  ADD_MEDIA_SUCCESS: null,
  ADD_MEDIA_FAILURE: null,

  GET_ACCOUNT_AGGREGATE_REQUEST: null,
  GET_ACCOUNT_AGGREGATE_SUCCESS: null,
  GET_ACCOUNT_AGGREGATE_FAILURE: null,

  ADD_GALLERY_MEDIA_REQUEST: null,
  ADD_GALLERY_MEDIA_SUCCESS: null,
  ADD_GALLERY_MEDIA_FAILURE: null,

  GET_MEDIA_GALLERY_REQUEST: null,
  GET_MEDIA_GALLERY_SUCCESS: null,
  GET_MEDIA_GALLERY_FAILURE: null,

  GET_MEDIA_REQUEST: null,
  GET_MEDIA_SUCCESS: null,
  GET_MEDIA_FAILURE: null,

  UPDATE_MEDIA_REQUEST: null,
  UPDATE_MEDIA_SUCCESS: null,
  UPDATE_MEDIA_FAILURE: null,

  SET_MEDIA_THUMB_IDX: null,

  REJECT_MEDIA_REQUEST: null,
  REJECT_MEDIA_SUCCESS: null,
  REJECT_MEDIA_FAILURE: null,

  UNDO_REJECT_MEDIA_REQUEST: null,
  UNDO_REJECT_MEDIA_SUCCESS: null,
  UNDO_REJECT_MEDIA_FAILURE: null,

  CHANGE_UGC_MEDIA_STATUS_REQUEST: null,
  CHANGE_UGC_MEDIA_STATUS_SUCCESS: null,
  CHANGE_UGC_MEDIA_STATUS_FAILURE: null,

  SOCIAL_MANAGEMENT_REDIRECT_REQUEST: null,
  SOCIAL_MANAGEMENT_REDIRECT_SUCCESS: null,
  SOCIAL_MANAGEMENT_REDIRECT_FAILURE: null,

  GET_SOCIAL_NETWORK_DATA_STORAGE_REQUEST: null,
  GET_SOCIAL_NETWORK_DATA_STORAGE_SUCCESS: null,
  GET_SOCIAL_NETWORK_DATA_STORAGE_FAILURE: null,

  RESET_SOCIAL_MANAGEMENT_REDIRECT: null,

  SOCIAL_MANAGEMENT_SAVE_PAGE_REQUEST: null,
  SOCIAL_MANAGEMENT_SAVE_PAGE_SUCCESS: null,
  SOCIAL_MANAGEMENT_SAVE_PAGE_FAILURE: null,

  FETCH_AUTH_SOCIAL_NETWORKS_REQUEST: null,
  FETCH_AUTH_SOCIAL_NETWORKS_SUCCESS: null,
  FETCH_AUTH_SOCIAL_NETWORKS_FAILURE: null,

  SOCIAL_MANAGEMENT_REMOVE_NETWORK_REQUEST: null,
  SOCIAL_MANAGEMENT_REMOVE_NETWORK_SUCCESS: null,
  SOCIAL_MANAGEMENT_REMOVE_NETWORK_FAILURE: null,

  SOCIAL_NETWORK_ADD_AUTHENTICATOR: null,

  GET_NOTIFICATIONS_REQUEST: null,
  GET_NOTIFICATIONS_SUCCESS: null,
  GET_NOTIFICATIONS_FAILURE: null,

  APPLY_GUEST_FILTERS: null,
  REMOVE_GUEST_FILTER: null,
  CLEAR_GUEST_FILTERS: null,
  CHANGE_GUEST_SEARCH_STRING: null,

  FETCH_GUEST_FILTER_PRESETS_REQUEST: null,
  FETCH_GUEST_FILTER_PRESETS_SUCCESS: null,
  FETCH_GUEST_FILTER_PRESETS_FAILURE: null,

  SAVE_GUEST_FILTER_PRESET_REQUEST: null,
  SAVE_GUEST_FILTER_PRESET_SUCCESS: null,
  SAVE_GUEST_FILTER_PRESETS_FAILURE: null,

  FETCH_ENTITY_FILTER_PARAMETERS_REQUEST: null,
  FETCH_ENTITY_FILTER_PARAMETERS_SUCCESS: null,
  FETCH_ENTITY_FILTER_PARAMETERS_FAILURE: null,

  FETCH_ENTITIES_REQUEST: null,
  FETCH_ENTITIES_SUCCESS: null,
  FETCH_ENTITIES_FAILURE: null,

  SET_ENTITY_DISPLAY_KEYS: null,
  SAVE_ENTITY_DISPLAY_KEYS: null,
  RESET_SAVE_ENTITY_DISPLAY_KEYS: null,

  UPDATE_CLIENT_NAME_REQUEST: null,
  UPDATE_CLIENT_NAME_SUCCESS: null,
  UPDATE_CLIENT_NAME_FAILURE: null,

  REMOVE_CLIENT_REQUEST: null,
  REMOVE_CLIENT_SUCCESS: null,
  REMOVE_CLIENT_FAILURE: null,

  SAVE_IMAGE_EDITING_REQUEST: null,
  SAVE_IMAGE_EDITING_SUCCESS: null,
  SAVE_IMAGE_EDITING_FAILURE: null,

  ADD_CONTACT_PROFILE_DATA_REQUEST: null,
  ADD_CONTACT_PROFILE_DATA_SUCCESS: null,
  ADD_CONTACT_PROFILE_DATA_FAILURE: null,

  ADD_PROFILE_LINE_REQUEST: null,
  ADD_PROFILE_LINE_SUCCESS: null,
  ADD_PROFILE_LINE_FAILURE: null,

  CHANGE_PROFILE_DATA_VALUE_REQUEST: null,
  CHANGE_PROFILE_DATA_VALUE_SUCCESS: null,
  CHANGE_PROFILE_DATA_VALUE_FAILURE: null,

  REMOVE_PROFILE_DATA_REQUEST: null,
  REMOVE_PROFILE_DATA_SUCCESS: null,
  REMOVE_PROFILE_DATA_FAILURE: null,

  FETCH_CONTACT_DETAIL_REQUEST: null,
  FETCH_CONTACT_DETAIL_SUCCESS: null,
  FETCH_CONTACT_DETAIL_FAILURE: null,

  ADD_CONTACT_COMPANY_DATA_REQUEST: null,
  ADD_CONTACT_COMPANY_DATA_SUCCESS: null,
  ADD_CONTACT_COMPANY_DATA_FAILURE: null,

  NEXT_CONTACT_ITEMS_SUCCESS: null,
  NEXT_CONTACT_ITEMS_REQUEST: null,
  NEXT_CONTACTS_LOAD_FAILURE: null,
  NEXT_CONTACT_PAGE: null,
  PREVIOUS_CONTACT_PAGE: null,
  CHANGE_CONTACT_PAGE: null,
  GET_SPECIFIC_CONTACT_PAGE_SUCCESS: null,
  GET_SPECIFIC_CONTACT_PAGE_REQUEST: null,

  UPLOAD_CUSTOM_MEDIA_TYPE_REQUEST: null,
  UPLOAD_CUSTOM_MEDIA_TYPE_SUCCESS: null,
  UPLOAD_CUSTOM_MEDIA_TYPE_FAILURE: null,

  GET_MEDIA_FROM_URL_REQUEST: null,
  GET_MEDIA_FROM_URL_SUCCESS: null,
  GET_MEDIA_FROM_URL_FAILURE: null,
  REMOVE_CRAWLED_IMAGE: null,
  CLEAR_CRAWLED_IMAGES: null,

  ADD_SORT_BY_OPTION: null,
  DELETE_SORT_BY_OPTION: null,
  DRAG_SORT_BY_OPTION: null,
  CHANGE_SORT_BY_OPTION_ORDER: null,

  ADD_CONTENT_FILTER_TAG_STAFF: null,
  REMOVE_CONTENT_FILTER_TAG_STAFF: null,

  ADD_CONTENT_FILTER_TAG_TAGS: null,
  REMOVE_CONTENT_FILTER_TAG_TAGS: null,

  ADD_TO_CONTACTS_SUCCESS: null,
  ADD_TO_AUDIENCE_SUCCESS: null,
  ADD_TO_CONTACTS_REQUEST: null,
  ADD_TO_AUDIENCE_REQUEST: null,
  ADD_TO_CONTACTS_FAILURE: null,
  ADD_TO_AUDIENCE_FAILURE: null,
  CLEAR_WORKFLOW_STATUS: null,

  SHOW_CONTENT_CYCLE_DETAILS: null,
  HIDE_CONTENT_CYCLE_DETAILS: null,
  SHOW_CREATE_TOPIC_MODAL: null,
  HIDE_CREATE_TOPIC_MODAL: null,
  SHOW_CREATE_POST_MODAL: null,
  HIDE_CREATE_POST_MODAL: null,
  EDIT_CONTENT_CYCLE_DETAILS: null,
  END_CONTENT_CYCLE_DETAILS_EDIT: null,
  SHOW_DELETE_CONFIRM_MODAL: null,
  HIDE_DELETE_CONFIRM_MODAL: null,

  SHOW_POST_DETAILS: null,

  CHANGE_CONTENT_SCHEDULER_VIEW_MODE: null,
  RESET_CONTENT_SCHEDULER_SETTINGS: null,
  SET_CONTENT_SCHEDULER_START_DATE: null,
  SET_CONTENT_SCHEDULER_END_DATE: null,
  SET_CONTENT_SCHEDULER_CURRENT_DATE: null,

  REJECT_POST_REQUEST: null,
  REJECT_POST_SUCCESS: null,
  REJECT_POST_ERROR: null,

  GET_CONTACT_DATA_TYPES_REQUEST: null,
  GET_CONTACT_DATA_TYPES_SUCCESS: null,
  GET_CONTACT_DATA_TYPES_FAILURE: null,

  FETCH_CLIENT_DETAIL_REQUEST: null,
  FETCH_CLIENT_DETAIL_SUCCESS: null,
  FETCH_CLIENT_DETAIL_FAILURE: null,

  FETCH_SETTINGS_ENTITIES_REQUEST: null,
  FETCH_SETTINGS_ENTITIES_SUCCESS: null,
  FETCH_SETTINGS_ENTITIES_FAILURE: null,

  SET_DEFAULT_ENTITY_REQUEST: null,
  SET_DEFAULT_ENTITY_SUCCESS: null,
  SET_DEFAULT_ENTITY_FAILURE: null,

  UPDATE_DEFAULT_ENTITY_REQUEST: null,
  UPDATE_DEFAULT_ENTITY_SUCCESS: null,
  UPDATE_DEFAULT_ENTITY_FAILURE: null,

  REMOVE_DEFAULT_ENTITY_REQUEST: null,
  REMOVE_DEFAULT_ENTITY_SUCCESS: null,
  REMOVE_DEFAULT_ENTITY_FAILURE: null,

  FETCH_COMPETITORS_REQUEST: null,
  FETCH_COMPETITORS_SUCCESS: null,
  FETCH_COMPETITORS_FAILURE: null,
  FETCH_COMPETITORS_CLEAR: null,

  ADD_CYCLE_COMMENT_REQUEST: null,
  ADD_CYCLE_COMMENT_SUCCESS: null,
  ADD_CYCLE_COMMENT_ERROR: null,

  GENERATE_SHORT_LINK_REQUEST: null,
  GENERATE_SHORT_LINK_SUCCESS: null,
  GENERATE_SHORT_LINK_FAILURE: null,
  CLEAR_SHORT_LINK: null,

  ADD_POST_COMMENT_REQUEST: null,
  ADD_POST_COMMENT_SUCCESS: null,
  ADD_POST_COMMENT_ERROR: null,

  CHANGE_SEARCH_BY_TYPE: null,

  EDIT_POST_CONTENT_REQUEST: null,
  EDIT_POST_CONTENT_SUCCESS: null,
  EDIT_POST_CONTENT_ERROR: null,

  LOCATION_AUTOCOMPLETE_REQUEST: null,
  LOCATION_AUTOCOMPLETE_SUCCESS: null,
  LOCATION_AUTOCOMPLETE_FAILURE: null,

  FETCH_SCHEDULER_SETTING_REQUEST: null,
  FETCH_SCHEDULER_SETTING_SUCCESS: null,
  FETCH_SCHEDULER_SETTING_FAILURE: null,

  CREATE_PILLAR_REQUEST: null,
  CREATE_PILLAR_SUCCESS: null,
  CREATE_PILLAR_FAILURE: null,
  UPDATE_PILLAR_REQUEST: null,
  UPDATE_PILLAR_SUCCESS: null,
  UPDATE_PILLAR_FAILURE: null,
  DELETE_PILLAR_REQUEST: null,
  DELETE_PILLAR_SUCCESS: null,
  DELETE_PILLAR_FAILURE: null,

  CREATE_POST_SCHEDULE_REQUEST: null,
  CREATE_POST_SCHEDULE_SUCCESS: null,
  CREATE_POST_SCHEDULE_FAILURE: null,
  UPDATE_POST_SCHEDULE_REQUEST: null,
  UPDATE_POST_SCHEDULE_SUCCESS: null,
  UPDATE_POST_SCHEDULE_FAILURE: null,
  DELETE_POST_SCHEDULE_REQUEST: null,
  DELETE_POST_SCHEDULE_SUCCESS: null,
  DELETE_POST_SCHEDULE_FAILURE: null,

  CHANGE_ROLE_ASSIGNEE_REQUEST: null,
  CHANGE_ROLE_ASSIGNEE_SUCCESS: null,
  CHANGE_ROLE_ASSIGNEE_FAILURE: null,

  UPDATE_CYCLE_DEFAULT_LENGTH_REQUEST: null,
  UPDATE_CYCLE_DEFAULT_LENGTH_SUCCESS: null,
  UPDATE_CYCLE_DEFAULT_LENGTH_FAILURE: null,

  EDIT_SCHEDULER_SETTING_DATA: null,
  RESET_DEFAULT_SCHEDULER_SETTINGS: null,

  SPECIFIC_CONTACT_CONVERSATION_PAGE: null,
  NEXT_CONTACT_CONVERSATIONS_REQUEST: null,
  NEXT_CONTACT_CONVERSATIONS_SUCCESS: null,
  NEXT_CONTACT_CONVERSATIONS_FAILURE: null,

  CREATE_CONTENT_CYCLE_REQUEST: null,
  CREATE_CONTENT_CYCLE_SUCCESS: null,
  CREATE_CONTENT_CYCLE_ERROR: null,

  FETCH_CONTENT_ACTIVITES_REQUEST: null,
  FETCH_CONTENT_ACTIVITES_SUCCESS: null,
  FETCH_CONTENT_ACTIVITES_FAILURE: null,

  GET_CLIENT_WEATHER_REQUEST: null,
  GET_CLIENT_WEATHER_SUCCESS: null,
  GET_CLIENT_WEATHER_ERROR: null,

  GET_CLIENT_WEEK_WEATHER_REQUEST: null,
  GET_CLIENT_WEEK_WEATHER_SUCCESS: null,
  GET_CLIENT_WEEK_WEATHER_ERROR: null,

  GET_CLIENT_CONTENT_REQUEST: null,
  GET_CLIENT_CONTENT_SUCCESS: null,
  GET_CLIENT_CONTENT_ERROR: null,

  OPEN_CYCLE_SELECTION_MODAL: null,
  CLOSE_CYCLE_SELECTION_MODAL: null,

  OPEN_MEDIA_SELECTION_MODAL: null,
  CLOSE_MEDIA_SELECTION_MODAL: null,

  START_EDIT_IMAGE_MODE: null,
  END_EDIT_IMAGE_MODE: null,

  CREATE_TOPIC_POST_REQUEST: null,
  CREATE_TOPIC_POST_SUCCESS: null,
  CREATE_TOPIC_POST_FAILURE: null,
  UPDATE_TOPIC_POST_REQUEST: null,
  UPDATE_TOPIC_POST_SUCCESS: null,
  UPDATE_TOPIC_POST_FAILURE: null,
  DELETE_TOPIC_POST_REQUEST: null,
  DELETE_TOPIC_POST_SUCCESS: null,
  DELETE_TOPIC_POST_FAILURE: null,

  MANAGE_TOPIC_POSTS_REQUEST: null,
  MANAGE_TOPIC_POSTS_SUCCESS: null,
  MANAGE_TOPIC_POSTS_FAILURE: null,
  CREATE_CONTENT_TOPIC_REQUEST: null,
  CREATE_CONTENT_TOPIC_SUCCESS: null,
  CREATE_CONTENT_TOPIC_FAILURE: null,

  DELETE_CONTENT_TOPIC_REQUEST: null,
  DELETE_CONTENT_TOPIC_SUCCESS: null,
  DELETE_CONTENT_TOPIC_ERROR: null,

  GET_CONTENT_CYCLE_DETAILS_REQUEST: null,
  GET_CONTENT_CYCLE_DETAILS_SUCCESS: null,
  GET_CONTENT_CYCLE_DETAILS_ERROR: null,

  CLEAR_CONTENT_CYCLE_DETAILS: null,

  GET_CYCLE_TOPICS_REQUEST: null,
  GET_CYCLE_TOPICS_SUCCESS: null,
  GET_CYCLE_TOPICS_ERROR: null,

  LOAD_MENTIONS_FROM_POST_REQUEST: null,
  LOAD_MENTIONS_FROM_POST_SUCCESS: null,
  LOAD_MENTIONS_FROM_POST_FAILURE: null,

  GET_TOPIC_POST_HISTORY_REQUEST: null,
  GET_TOPIC_POST_HISTORY_SUCCESS: null,
  GET_TOPIC_POST_HISTORY_ERROR: null,

  FETCH_POSTS_APPROVAL_REQUEST: null,
  FETCH_POSTS_APPROVAL_SUCCESS: null,
  FETCH_POSTS_APPROVAL_FAILURE: null,

  ENTER_CONTENT_CYCLE_STANDARD_VIEW: null,
  ENTER_CONTENT_CYCLE_DRAFT_MODE: null,
  END_CONTENT_CYCLE_DRAFT_MODE: null,
  OPEN_NEW_CONTENT_CYCLE_MODAL: null,
  CLOSE_NEW_CONTENT_CYCLE_MODAL: null,

  UPDATE_CONTENT_CYCLE_REQUEST: null,
  UPDATE_CONTENT_CYCLE_SUCCESS: null,
  UPDATE_CONTENT_CYCLE_ERROR: null,

  DELETE_CLIENT_CONTENT_CYCLE_REQUEST: null,
  DELETE_CLIENT_CONTENT_CYCLE_SUCCESS: null,
  DELETE_CLIENT_CONTENT_CYCLE_FAILURE: null,
  DUPLICATE_CLIENT_CONTENT_CYCLE_REQUEST: null,
  DUPLICATE_CLIENT_CONTENT_CYCLE_SUCCESS: null,
  DUPLICATE_CLIENT_CONTENT_CYCLE_FAILURE: null,

  CHANGE_TOPIC_POST_STATUS_REQUEST: null,
  CHANGE_TOPIC_POST_STATUS_SUCCESS: null,
  CHANGE_TOPIC_POST_STATUS_FAILURE: null,

  CHANGE_TOPIC_POST_STATUS_BULK_REQUEST: null,
  CHANGE_TOPIC_POST_STATUS_BULK_SUCCESS: null,
  CHANGE_TOPIC_POST_STATUS_BULK_FAILURE: null,

  AGENT_REVIEW_REQUEST_EDIT_REQUEST: null,
  AGENT_REVIEW_REQUEST_EDIT_SUCCESS: null,
  AGENT_REVIEW_REQUEST_EDIT_FAILURE: null,
  AGENT_REVIEW_REJECT_REQUEST: null,
  AGENT_REVIEW_REJECT_SUCCESS: null,
  AGENT_REVIEW_REJECT_FAILURE: null,
  AGENT_REVIEW_APPROVE_REQUEST: null,
  AGENT_REVIEW_APPROVE_SUCCESS: null,
  AGENT_REVIEW_APPROVE_FAILURE: null,

  APPLY_TOPIC_POSTS_STAGE_CHANGE_REQUEST: null,
  APPLY_TOPIC_POSTS_STAGE_CHANGE_SUCCESS: null,
  APPLY_TOPIC_POSTS_STAGE_CHANGE_FAILURE: null,

  FEEDBACK_APPROVE_REQUEST: null,
  FEEDBACK_APPROVE_SUCCESS: null,
  FEEDBACK_APPROVE_ERROR: null,
  FEEDBACK_REJECT_REQUEST: null,
  FEEDBACK_REJECT_SUCCESS: null,
  FEEDBACK_REJECT_ERROR: null,
  FEEDBACK_REQUEST_EDIT_REQUEST: null,
  FEEDBACK_REQUEST_EDIT_SUCCESS: null,
  FEEDBACK_REQUEST_EDIT_ERROR: null,
  FEEDBACK_REVISE_REQUEST: null,
  FEEDBACK_REVISE_SUCCESS: null,
  FEEDBACK_REVISE_ERROR: null,

  RESCHEDULE_TOPIC_POST_REQUEST: null,
  RESCHEDULE_TOPIC_POST_SUCCESS: null,
  RESCHEDULE_TOPIC_POST_ERROR: null,

  FETCH_CONTENT_CYCLES_REQUEST: null,
  FETCH_CONTENT_CYCLES_SUCCESS: null,
  FETCH_CONTENT_CYCLES_FAILURE: null,

  EDIT_TOPIC_DETAILS_REQUEST: null,
  EDIT_TOPIC_DETAILS_SUCCESS: null,
  EDIT_TOPIC_DETAILS_ERROR: null,

  REJECT_APPROVAL_POST_REQUEST: null,
  REJECT_APPROVAL_POST_SUCCESS: null,
  REJECT_APPROVAL_POST_FAILURE: null,

  REQUEST_EDIT_APPROVAL_POST_REQUEST: null,
  REQUEST_EDIT_APPROVAL_POST_SUCCESS: null,
  REQUEST_EDIT_APPROVAL_POST_FAILURE: null,

  MAKE_EDIT_APPROVAL_POST_REQUEST: null,
  MAKE_EDIT_APPROVAL_POST_SUCCESS: null,
  MAKE_EDIT_APPROVAL_POST_FAILURE: null,

  ACCEPT_APPROVAL_POST_REQUEST: null,
  ACCEPT_APPROVAL_POST_SUCCESS: null,
  ACCEPT_APPROVAL_POST_FAILURE: null,

  REJECT_ALL_APPROVAL_POSTS_REQUEST: null,
  REJECT_ALL_APPROVAL_POSTS_SUCCESS: null,
  REJECT_ALL_APPROVAL_POSTS_FAILURE: null,

  REQUEST_APPROVAL_EDITS_ALL_POSTS_REQUEST: null,
  REQUEST_APPROVAL_EDITS_ALL_POSTS_SUCCESS: null,
  REQUEST_APPROVAL_EDITS_ALL_POSTS_FAILURE: null,

  APPROVE_ALL_AGENT_REVIEW_POSTS_REQUEST: null,
  APPROVE_ALL_AGENT_REVIEW_POSTS_SUCCESS: null,
  APPROVE_ALL_AGENT_REVIEW_POSTS_FAILURE: null,

  FETCH_FEEDBACK_POSTS_REQUEST: null,
  FETCH_FEEDBACK_POSTS_SUCCESS: null,
  FETCH_FEEDBACK_POSTS_FAILURE: null,

  FETCH_SCHEDULED_POSTS_REQUEST: null,
  FETCH_SCHEDULED_POSTS_SUCCESS: null,
  FETCH_SCHEDULED_POSTS_FAILURE: null,

  FILTER_TOPIC_POSTS_REQUEST: null,
  FILTER_TOPIC_POSTS_SUCCESS: null,
  FILTER_TOPIC_POSTS_ERROR: null,

  GET_ASSIGNED_STAFF_REQUEST: null,
  GET_ASSIGNED_STAFF_SUCCESS: null,
  GET_ASSIGNED_STAFF_ERROR: null,

  GET_MEDIA_ASSET_TYPES_REQUEST: null,
  GET_MEDIA_ASSET_TYPES_SUCCESS: null,
  GET_MEDIA_ASSET_TYPES_FAILURE: null,

  GET_CLIENT_COMMENTS_REQUEST: null,
  GET_CLIENT_COMMENTS_SUCCESS: null,
  GET_CLIENT_COMMENTS_ERROR: null,

  APPLY_BULK_TOPIC_ACTION_REQUEST: null,
  APPLY_BULK_TOPIC_ACTION_SUCCESS: null,
  APPLY_BULK_TOPIC_ACTION_FAILURE: null,

  FETCH_NETWORK_TYPES_REQUEST: null,
  FETCH_NETWORK_TYPES_SUCCESS: null,
  FETCH_NETWORK_TYPES_FAILURE: null,

  GET_HOLIDAYS_REQUEST: null,
  GET_HOLIDAYS_SUCCESS: null,
  GET_HOLIDAYS_ERROR: null,

  CREATE_COMPETITOR_GROUP_REQUEST: null,
  CREATE_COMPETITOR_GROUP_SUCCESS: null,
  CREATE_COMPETITOR_GROUP_FAILURE: null,

  FETCH_COMPETITOR_GROUPS_REQUEST: null,
  FETCH_COMPETITOR_GROUPS_SUCCESS: null,
  FETCH_COMPETITOR_GROUPS_FAILURE: null,

  DUPLICATE_COMPETITOR_GROUP_REQUEST: null,
  DUPLICATE_COMPETITOR_GROUP_SUCCESS: null,
  DUPLICATE_COMPETITOR_GROUP_FAILURE: null,

  FETCH_COMPETITOR_GROUP_DETAIL_REQUEST: null,
  FETCH_COMPETITOR_GROUP_DETAIL_SUCCESS: null,
  FETCH_COMPETITOR_GROUP_DETAIL_FAILURE: null,

  REMOVE_COMPETITOR_GROUP_REQUEST: null,
  REMOVE_COMPETITOR_GROUP_SUCCESS: null,
  REMOVE_COMPETITOR_GROUP_FAILURE: null,

  SET_DEFAULT_COMPETITOR_GROUP_REQUEST: null,
  SET_DEFAULT_COMPETITOR_GROUP_SUCCESS: null,
  SET_DEFAULT_COMPETITOR_GROUP_FAILURE: null,

  UPDATE_COMPETITOR_GROUP_REQUEST: null,
  UPDATE_COMPETITOR_GROUP_SUCCESS: null,
  UPDATE_COMPETITOR_GROUP_FAILURE: null,

  FETCH_CLIENT_ALERT_TYPES_REQUEST: null,
  FETCH_CLIENT_ALERT_TYPES_SUCCESS: null,
  FETCH_CLIENT_ALERT_TYPES_FAILURE: null,

  FETCH_DEFAULT_ALERT_TYPES_REQUEST: null,
  FETCH_DEFAULT_ALERT_TYPES_SUCCESS: null,
  FETCH_DEFAULT_ALERT_TYPES_FAILURE: null,

  ADD_ALERT_TYPE_FOR_CLIENT_REQUEST: null,
  ADD_ALERT_TYPE_FOR_CLIENT_SUCCESS: null,
  ADD_ALERT_TYPE_FOR_CLIENT_FAILURE: null,

  REMOVE_ALERT_TYPE_FOR_CLIENT_REQUEST: null,
  REMOVE_ALERT_TYPE_FOR_CLIENT_SUCCESS: null,
  REMOVE_ALERT_TYPE_FOR_CLIENT_FAILURE: null,

  SET_CURRENT_SETTINGS_ALERT_TYPE_ID: null,

  ADD_ALERT_TYPE_USER_REQUEST: null,
  ADD_ALERT_TYPE_USER_SUCCESS: null,
  ADD_ALERT_TYPE_USER_FAILURE: null,

  REMOVE_ALERT_TYPE_USER_REQUEST: null,
  REMOVE_ALERT_TYPE_USER_SUCCESS: null,
  REMOVE_ALERT_TYPE_USER_FAILURE: null,

  FETCH_CLIENT_STREAM_TYPES_REQUEST: null,
  FETCH_CLIENT_STREAM_TYPES_SUCCESS: null,
  FETCH_CLIENT_STREAM_TYPES_FAILURE: null,

  FETCH_CLIENT_STREAMS_REQUEST: null,
  FETCH_CLIENT_STREAMS_SUCCESS: null,
  FETCH_CLIENT_STREAMS_FAILURE: null,

  ADD_CLIENT_STREAMS_REQUEST: null,
  ADD_CLIENT_STREAMS_SUCCESS: null,
  ADD_CLIENT_STREAMS_FAILURE: null,

  REMOVE_CLIENT_STREAMS_REQUEST: null,
  REMOVE_CLIENT_STREAMS_SUCCESS: null,
  REMOVE_CLIENT_STREAMS_FAILURE: null,

  UPDATE_CLIENT_STREAMS_REQUEST: null,
  UPDATE_CLIENT_STREAMS_SUCCESS: null,
  UPDATE_CLIENT_STREAMS_FAILURE: null,

  SUBSCRIPTION_CLIENT_STREAMS_REQUEST: null,
  SUBSCRIPTION_CLIENT_STREAMS_SUCCESS: null,
  SUBSCRIPTION_CLIENT_STREAMS_FAILURE: null,

  FETCH_NEXT_FACEBOOK_PAGES_REQUEST: null,
  FETCH_NEXT_FACEBOOK_PAGES_SUCCESS: null,

  CREATE_NEW_USER_REQUEST: null,
  CREATE_NEW_USER_SUCCESS: null,
  CREATE_NEW_USER_FAILURE: null,

  ADD_EXISTING_USER_AS_PEOPLE_REQUEST: null,
  ADD_EXISTING_USER_AS_PEOPLE_SUCCESS: null,
  ADD_EXISTING_USER_AS_PEOPLE_FAILURE: null,

  CHANGE_PEOPLE_PASSWORD_REQUEST: null,
  CHANGE_PEOPLE_PASSWORD_SUCCESS: null,
  CHANGE_PEOPLE_PASSWORD_FAILURE: null,

  CLIENTS_HAS_NEXT_PAGE_SUCCESS: null,

  GET_ENTITY_EXPLORER_DATA_REQUEST: null,
  GET_ENTITY_EXPLORER_DATA_SUCCESS: null,
  GET_ENTITY_EXPLORER_DATA_FAILURE: null,

  GET_ENTITY_GROUPS_REQUEST: null,
  GET_ENTITY_GROUPS_SUCCESS: null,
  GET_ENTITY_GROUPS_FAILURE: null,

  SAVE_EXPLORER_TABLE_DISPLAYING_FIELDS: null,
  UPDATE_ENTITY_FILTER: null,
  CLEAR_ENTITY_FILTERS: null,

  SEARCH_ENTITIES_REQUEST: null,
  SEARCH_ENTITIES_CSV_REQUEST: null,
  SEARCH_ENTITIES_SUCCESS: null,
  SEARCH_ENTITIES_CSV_SUCCESS: null,
  SEARCH_ENTITIES_FAILURE: null,

  SEARCH_ENTITY_BRAND_REQUEST: null,
  SEARCH_ENTITY_BRAND_SUCCESS: null,
  SEARCH_ENTITY_BRAND_FAILURE: null,

  SEARCH_ENTITY_COMPETITOR_REQUEST: null,
  SEARCH_ENTITY_COMPETITOR_SUCCESS: null,
  SEARCH_ENTITY_COMPETITOR_FAILURE: null,

  CREATE_ENTITY_REQUEST: null,
  CREATE_ENTITY_SUCCESS: null,
  CREATE_ENTITY_FAILURE: null,
  UPDATE_ENTITY_REQUEST: null,
  UPDATE_ENTITY_SUCCESS: null,
  UPDATE_ENTITY_FAILURE: null,

  ADD_ENTITY_SOCIAL_ACCOUNT_REQUEST: null,
  ADD_ENTITY_SOCIAL_ACCOUNT_SUCCESS: null,
  ADD_ENTITY_SOCIAL_ACCOUNT_FAILURE: null,

  BULK_ASSIGN_COLLABORATORS_REQUEST: null,
  BULK_ASSIGN_COLLABORATORS_SUCCESS: null,
  BULK_ASSIGN_COLLABORATORS_FAILURE: null,

  BULK_UNASSIGN_COLLABORATORS_REQUEST: null,
  BULK_UNASSIGN_COLLABORATORS_SUCCESS: null,
  BULK_UNASSIGN_COLLABORATORS_FAILURE: null,

  FETCH_CLIENT_NOTES_REQUEST: null,
  FETCH_CLIENT_NOTES_SUCCESS: null,
  FETCH_CLIENT_NOTES_FAILURE: null,

  UPDATE_CLIENT_NOTE_REQUEST: null,
  UPDATE_CLIENT_NOTE_SUCCESS: null,
  UPDATE_CLIENT_NOTE_FAILURE: null,

  REMOVE_CLIENT_NOTE_REQUEST: null,
  REMOVE_CLIENT_NOTE_SUCCESS: null,
  REMOVE_CLIENT_NOTE_FAILURE: null,

  CREATE_CLIENT_NOTE_REQUEST: null,
  CREATE_CLIENT_NOTE_SUCCESS: null,
  CREATE_CLIENT_NOTE_FAILURE: null,

  SOCIAL_USERNAME_AUTO_SUGGESTIONS_REQUEST: null,
  SOCIAL_USERNAME_AUTO_SUGGESTIONS_SUCCESS: null,
  SOCIAL_USERNAME_AUTO_SUGGESTIONS_FAILURE: null,
  SOCIAL_USERNAME_AUTO_SUGGESTIONS_RESET: null,

  EXPORT_CONTENT_CYCLE_REQUEST: null,
  EXPORT_CONTENT_CYCLE_FAILURE: null,
  EXPORT_CONTENT_CYCLE_SUCCESS: null,

  CLEAR_LOCATIONS_SEARCH_RESULTS: null,

  GET_FACEBOOK_LOCATION_REQUEST: null,
  GET_FACEBOOK_LOCATION_SUCCESS: null,
  GET_FACEBOOK_LOCATION_FAILURE: null,

  GET_INSTAGRAM_LOCATION_REQUEST: null,
  GET_INSTAGRAM_LOCATION_SUCCESS: null,
  GET_INSTAGRAM_LOCATION_FAILURE: null,

  REMOVE_ENTITY_SOCIAL_ACCOUNT_REQUEST: null,
  REMOVE_ENTITY_SOCIAL_ACCOUNT_SUCCESS: null,
  REMOVE_ENTITY_SOCIAL_ACCOUNT_FAILURE: null,

  ADD_ENTITY_LOCATION_REQUEST: null,
  ADD_ENTITY_LOCATION_SUCCESS: null,
  ADD_ENTITY_LOCATION_FAILURE: null,

  REMOVE_ENTITY_LOCATION_REQUEST: null,
  REMOVE_ENTITY_LOCATION_SUCCESS: null,
  REMOVE_ENTITY_LOCATION_FAILURE: null,

  AUTH_IG_GRAPH_REQUEST: null,
  AUTH_IG_GRAPH_SUCCESS: null,
  AUTH_IG_GRAPH_FAILURE: null,

  UPDATE_USER_SYSTEM_ROLE_REQUEST: null,
  UPDATE_USER_SYSTEM_ROLE_SUCCESS: null,
  UPDATE_USER_SYSTEM_ROLE_FAILURE: null,

  /* for changing user system roles */
  CHANGE_USER_SYSTEM_ROLE_REQUEST: null,
  CHANGE_USER_SYSTEM_ROLE_SUCCESS: null,
  CHANGE_USER_SYSTEM_ROLE_FAILURE: null,

  FETCH_TIMEZONE_REQUEST: null,
  FETCH_TIMEZONE_SUCCESS: null,
  FETCH_TIMEZONE_FAILURE: null,

  HIDE_MODAL: null,
  SHOW_MODAL: null,

  RESTORE_DELETED_CLIENT_REQUEST: null,
  RESTORE_DELETED_CLIENT_SUCCESS: null,
  RESTORE_DELETED_CLIENT_FAILURE: null,

  FETCH_CYCLE_POSTS_REQUEST: null,
  FETCH_CYCLE_POSTS_SUCCESS: null,
  FETCH_CYCLE_POSTS_FAILURE: null,

  FETCH_AD_CAMPAIGNS_REQUEST: null,
  FETCH_AD_CAMPAIGNS_SUCCESS: null,
  FETCH_AD_CAMPAIGNS_FAILURE: null,

  DOWNLOAD_ALERTS_REPORT_REQUEST: null,
  DOWNLOAD_ALERTS_REPORT_SUCCESS: null,
  DOWNLOAD_ALERTS_REPORT_FAILURE: null,

  TOGGLE_PAUSE_CONTENT_SCHEDULING_REQUEST: null,
  TOGGLE_PAUSE_CONTENT_SCHEDULING_SUCCESS: null,
  TOGGLE_PAUSE_CONTENT_SCHEDULING_FAILURE: null,

  GET_SCHEDULED_POSTS_REQUEST: null,
  GET_SCHEDULED_POSTS_SUCCESS: null,
  GET_SCHEDULED_POSTS_FAILURE: null,

  SET_SCHEDULED_POSTS_DATE: null,

  GET_CLIENT_AD_ACCOUNTS_REQUEST: null,
  GET_CLIENT_AD_ACCOUNTS_SUCCESS: null,
  GET_CLIENT_AD_ACCOUNTS_FAILURE: null,

  ATTACH_CLIENT_AD_ACCOUNT_REQUEST: null,
  ATTACH_CLIENT_AD_ACCOUNT_SUCCESS: null,
  ATTACH_CLIENT_AD_ACCOUNT_FAILURE: null,

  REMOVE_CLIENT_AD_ACCOUNT_REQUEST: null,
  REMOVE_CLIENT_AD_ACCOUNT_SUCCESS: null,
  REMOVE_CLIENT_AD_ACCOUNT_FAILURE: null,

  GET_INBOX_MESSAGES_REQUEST: null,
  GET_INBOX_MESSAGES_SUCCESS: null,
  GET_INBOX_MESSAGES_FAILURE: null,
  SELECT_INBOX_MESSAGE: null,
  SELECT_ALL_INBOX_MESSAGES: null,

  ARCHIVE_INBOX_MESSAGE_REQUEST: null,
  ARCHIVE_INBOX_MESSAGE_SUCCESS: null,
  ARCHIVE_INBOX_MESSAGE_FAILURE: null,

  LIKE_INBOX_MESSAGE_REQUEST: null,
  LIKE_INBOX_MESSAGE_SUCCESS: null,
  LIKE_INBOX_MESSAGE_FAILURE: null,

  DISLIKE_INBOX_MESSAGE_REQUEST: null,
  DISLIKE_INBOX_MESSAGE_SUCCESS: null,
  DISLIKE_INBOX_MESSAGE_FAILURE: null,

  GET_INBOX_ARCHIVE_MESSAGES_REQUEST: null,
  GET_INBOX_ARCHIVE_MESSAGES_SUCCESS: null,
  GET_INBOX_ARCHIVE_MESSAGES_FAILURE: null,

  GET_INBOX_CONVERSATIONS_REQUEST: null,
  GET_INBOX_CONVERSATIONS_SUCCESS: null,
  GET_INBOX_CONVERSATIONS_FAILURE: null,

  GET_INBOX_CLIENT_HISTORY_REQUEST: null,
  GET_INBOX_CLIENT_HISTORY_SUCCESS: null,
  GET_INBOX_CLIENT_HISTORY_FAILURE: null,

  GET_PROPERTY_ALERT_MESSAGES_REQUEST: null,
  GET_PROPERTY_ALERT_MESSAGES_SUCCESS: null,
  GET_PROPERTY_ALERT_MESSAGES_FAILURE: null,

  UPDATE_PROPERTY_ALERT_MESSAGES_REQUEST: null,
  UPDATE_PROPERTY_ALERT_MESSAGES_SUCCESS: null,
  UPDATE_PROPERTY_ALERT_MESSAGES_FAILURE: null,

  GET_INBOX_AUTO_SUGGESTED_CLIENTS_REQUEST: null,
  GET_INBOX_AUTO_SUGGESTED_CLIENTS_SUCCESS: null,
  GET_INBOX_AUTO_SUGGESTED_CLIENTS_FAILURE: null,

  POST_INBOX_FACEBOOK_REPLY_REQUEST: null,
  POST_INBOX_FACEBOOK_REPLY_SUCCESS: null,
  POST_INBOX_FACEBOOK_REPLY_FAILURE: null,

  POST_INBOX_FACEBOOK_CONVERSATION_REPLY_REQUEST: null,
  POST_INBOX_FACEBOOK_CONVERSATION_REPLY_SUCCESS: null,
  POST_INBOX_FACEBOOK_CONVERSATION_REPLY_FAILURE: null,

  SELECT_INBOX_SUGGESTED_CLIENTS: null,
  DESELECT_INBOX_SUGGESTED_CLIENTS: null,
  CLEAR_SELECTED_INBOX_SUGGESTED_CLIENTS: null,

  UPDATE_INBOX_MESSAGE_FILTERS: null,
  CLEAR_ALL_SELECTED_INBOX_MESSAGE_FILTERS: null,

  GET_INBOX_FILTER_OPTIONS_REQUEST: null,
  GET_INBOX_FILTER_OPTIONS_SUCCESS: null,
  GET_INBOX_FILTER_OPTIONS_FAILURE: null,

  REQUEST_UGC_PERMISSION_REQUEST: null,
  REQUEST_UGC_PERMISSION_SUCCESS: null,
  REQUEST_UGC_PERMISSION_FAILURE: null,

  POST_MESSAGE_MEDIA_UGC_APPROVAL_REQUEST: null,
  POST_MESSAGE_MEDIA_UGC_APPROVAL_SUCCESS: null,
  POST_MESSAGE_MEDIA_UGC_APPROVAL_FAILURE: null,

  POST_INBOX_INSTAGRAM_CONVERSATION_REPLY_REQUEST: null,
  POST_INBOX_INSTAGRAM_CONVERSATION_REPLY_SUCCESS: null,
  POST_INBOX_INSTAGRAM_CONVERSATION_REPLY_FAILURE: null,

  POST_INBOX_INSTAGRAM_REPLY_REQUEST: null,
  POST_INBOX_INSTAGRAM_REPLY_SUCCESS: null,
  POST_INBOX_INSTAGRAM_REPLY_FAILURE: null,

  GET_PENDING_ITEM_FILTER_OPTIONS_REQUEST: null,
  GET_PENDING_ITEM_FILTER_OPTIONS_SUCCESS: null,
  GET_PENDING_ITEM_FILTER_OPTIONS_FAILURE: null,

  CREATE_EVENT_ALERT_REQUEST: null,
  CREATE_EVENT_ALERT_SUCCESS: null,
  CREATE_EVENT_ALERT_FAILURE: null,

  CREATE_USER_ALERT_REQUEST: null,
  CREATE_USER_ALERT_SUCCESS: null,
  CREATE_USER_ALERT_FAILURE: null,

  POST_INBOX_TWITTER_REPLY_REQUEST: null,
  POST_INBOX_TWITTER_REPLY_SUCCESS: null,
  POST_INBOX_TWITTER_REPLY_FAILURE: null,

  POST_INBOX_TWITTER_CONVERSATION_REPLY_REQUEST: null,
  POST_INBOX_TWITTER_CONVERSATION_REPLY_SUCCESS: null,
  POST_INBOX_TWITTER_CONVERSATION_REPLY_FAILURE: null,

  EDIT_USER_ALERT_REQUEST: null,
  EDIT_USER_ALERT_SUCCESS: null,
  EDIT_USER_ALERT_FAILURE: null,

  EDIT_EVENT_ALERT_REQUEST: null,
  EDIT_EVENT_ALERT_SUCCESS: null,
  EDIT_EVENT_ALERT_FAILURE: null,

  GET_CLIENT_PRIORITY_MONITORING_SETTINGS_REQUEST: null,
  GET_CLIENT_PRIORITY_MONITORING_SETTINGS_SUCCESS: null,
  GET_CLIENT_PRIORITY_MONITORING_SETTINGS_FAILURE: null,

  EDIT_CLIENT_PRIORITY_MONITORING_SETTINGS_REQUEST: null,
  EDIT_CLIENT_PRIORITY_MONITORING_SETTINGS_SUCCESS: null,
  EDIT_CLIENT_PRIORITY_MONITORING_SETTINGS_FAILURE: null,

  UNARCHIVE_INBOX_MESSAGE_REQUEST: null,
  UNARCHIVE_INBOX_MESSAGE_SUCCESS: null,
  UNARCHIVE_INBOX_MESSAGE_FAILURE: null,

  GET_CLIENT_NOTES_REQUEST: null,
  GET_CLIENT_NOTES_SUCCESS: null,
  GET_CLIENT_NOTES_FAILURE: null,

  GET_INBOX_PROPERTY_ALERTS_REQUEST: null,
  GET_INBOX_PROPERTY_ALERTS_SUCCESS: null,
  GET_INBOX_PROPERTY_ALERTS_FAILURE: null,

  UPDATE_PROPERTY_ALERT_FILTERS: null,

  GET_INBOX_MESSAGE_TYPES_REQUEST: null,
  GET_INBOX_MESSAGE_TYPES_SUCCESS: null,
  GET_INBOX_MESSAGE_TYPES_FAILURE: null,

  CLEAR_INBOX_AUTOSUGGESTED_CLIENTS: null,

  GET_INBOX_PENDING_ITEMS_REQUEST: null,
  GET_INBOX_PENDING_ITEMS_SUCCESS: null,
  GET_INBOX_PENDING_ITEMS_FAILURE: null,

  UPDATE_PENDING_ITEMS_FILTERS: null,

  GET_INBOX_CLIENT_ALERT_TYPE_FILTER_OPTIONS_REQUEST: null,
  GET_INBOX_CLIENT_ALERT_TYPE_FILTER_OPTIONS_SUCCESS: null,
  GET_INBOX_CLIENT_ALERT_TYPE_FILTER_OPTIONS_FAILURE: null,

  BULK_ARCHIVE_INBOX_MESSAGES_REQUEST: null,
  BULK_ARCHIVE_INBOX_MESSAGES_SUCCESS: null,
  BULK_ARCHIVE_INBOX_MESSAGES_FAILURE: null,

  POST_INBOX_TRANSLATE_REPLY_REQUEST: null,
  POST_INBOX_TRANSLATE_REPLY_SUCCESS: null,
  POST_INBOX_TRANSLATE_REPLY_FAILURE: null,

  LIKE_INBOX_CONVERSATION_REQUEST: null,
  LIKE_INBOX_CONVERSATION_SUCCESS: null,
  LIKE_INBOX_CONVERSATION_FAILURE: null,

  DISLIKE_INBOX_CONVERSATION_REQUEST: null,
  DISLIKE_INBOX_CONVERSATION_SUCCESS: null,
  DISLIKE_INBOX_CONVERSATION_FAILURE: null,

  GET_CLIENT_TONE_OF_VOICE_REQUEST: null,
  GET_CLIENT_TONE_OF_VOICE_SUCCESS: null,
  GET_CLIENT_TONE_OF_VOICE_FAILURE: null,

  GET_USER_ACTION_DETAIL_REQUEST: null,
  GET_USER_ACTION_DETAIL_SUCCESS: null,
  GET_USER_ACTION_DETAIL_FAILURE: null,

  POST_MESSAGE_VIEW_USER_ACTION_REQUEST: null,
  POST_MESSAGE_VIEW_USER_ACTION_SUCCESS: null,
  POST_MESSAGE_VIEW_USER_ACTION_FAILURE: null
})
export default ResetPassword
export default ForgetPassword
export default NoteLoad
export default ActionTypes